# Copyright (c) 2026 kogeler
# SPDX-License-Identifier: MIT

"""Build exact GitHub dependency manifests from Elsewindow's hash locks."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from urllib.parse import quote

DEFAULT_ROOT = Path(__file__).resolve().parents[2]
AUDIENCES = ("quality", "test", "package", "standalone", "docs")
LOCK_NAMES = (
    "requirements.txt",
    *(f"requirements-{audience}.txt" for audience in AUDIENCES),
)
LOCK_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)\s+\\$")
LOCK_HASH = re.compile(r"^--hash=sha256:([0-9a-f]{64})(?:\s+\\)?$")
DIRECT_REQUIREMENT = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9._-]*)"
    r"(?:\[[A-Za-z0-9._-]+(?:,[A-Za-z0-9._-]+)*\])?==([^\s;]+)$"
)
INPUT_INCLUDE = re.compile(r"^-r ([^\s]+)$")


class SnapshotError(ValueError):
    """Dependency inputs cannot produce an exact snapshot."""


def normalize_package(name: str) -> str:
    """Normalize a PyPI project name according to PEP 503."""
    return re.sub(r"[-_.]+", "-", name).casefold()


def _validate_project(path: Path) -> None:
    """Validate the one-way package metadata link to the runtime input."""
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise SnapshotError(f"cannot read {path}: {error}") from error
    project = document.get("project")
    if not isinstance(project, dict):
        raise SnapshotError(f"{path}: missing [project] table")
    if project.get("dynamic") != ["version", "dependencies"]:
        raise SnapshotError(
            f"{path}: [project].dynamic must be ['version', 'dependencies']"
        )
    if "dependencies" in project or "optional-dependencies" in project:
        raise SnapshotError(
            f"{path}: dependency versions must exist only in requirements inputs"
        )

    tool = document.get("tool")
    setuptools = tool.get("setuptools") if isinstance(tool, dict) else None
    dynamic = setuptools.get("dynamic") if isinstance(setuptools, dict) else None
    if not isinstance(dynamic, dict) or dynamic.get("dependencies") != {
        "file": ["requirements.in"]
    }:
        raise SnapshotError(
            f"{path}: [tool.setuptools.dynamic].dependencies must read requirements.in"
        )


def direct_requirements(
    path: Path, *, runtime_input: Path | None = None
) -> dict[str, str]:
    """Return exact direct pins from one constrained requirements input."""
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as error:
        raise SnapshotError(f"cannot read {path}: {error}") from error

    direct: dict[str, str] = {}
    includes: list[str] = []
    for line_number, line in enumerate(content.splitlines(), start=1):
        requirement = line.strip()
        if not requirement or requirement.startswith("#"):
            continue
        include_match = INPUT_INCLUDE.fullmatch(requirement)
        if include_match is not None:
            includes.append(include_match.group(1))
            continue
        match = DIRECT_REQUIREMENT.fullmatch(requirement)
        if match is None:
            raise SnapshotError(
                f"{path}:{line_number}: dependency must be one exact PyPI pin"
            )
        name = normalize_package(match.group(1))
        if name in direct:
            raise SnapshotError(f"{path}: duplicate direct dependency: {name}")
        direct[name] = match.group(2)
    if not direct:
        raise SnapshotError(f"{path}: input contains no direct dependency pins")

    if runtime_input is None:
        if includes:
            raise SnapshotError(
                f"{path}: independent input cannot include another file"
            )
        return direct

    expected_include = runtime_input.name
    if includes != [expected_include]:
        raise SnapshotError(
            f"{path}: must include exactly '-r {expected_include}' once"
        )
    runtime = direct_requirements(runtime_input)
    duplicates = sorted(set(runtime) & set(direct))
    if duplicates:
        raise SnapshotError(
            f"{path}: runtime dependencies repeated locally: {', '.join(duplicates)}"
        )
    return runtime | direct


def read_lock(path: Path) -> dict[str, str]:
    """Read exact pins from a pip-compile hash lock and reject unknown syntax."""
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as error:
        raise SnapshotError(f"cannot read {path}: {error}") from error
    if "autogenerated by pip-compile" not in content:
        raise SnapshotError(f"{path}: missing pip-compile generated header")

    pins: dict[str, str] = {}
    current_name: str | None = None
    current_version = ""
    current_hashes: set[str] = set()

    def finish_pin() -> None:
        nonlocal current_name, current_version, current_hashes
        if current_name is None:
            return
        if not current_hashes:
            raise SnapshotError(
                f"{path}: {current_name}=={current_version} has no SHA-256 hash"
            )
        pins[current_name] = current_version
        current_name = None
        current_version = ""
        current_hashes = set()

    for line_number, line in enumerate(content.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line[:1].isspace():
            match = LOCK_HASH.fullmatch(stripped)
            if match is None or current_name is None:
                raise SnapshotError(
                    f"{path}:{line_number}: unsupported lock continuation"
                )
            digest = match.group(1)
            if digest in current_hashes:
                raise SnapshotError(f"{path}:{line_number}: duplicate SHA-256 hash")
            current_hashes.add(digest)
            continue
        match = LOCK_PIN.fullmatch(line)
        if match is None:
            raise SnapshotError(f"{path}:{line_number}: unsupported lock entry")
        finish_pin()
        current_name = normalize_package(match.group(1))
        current_version = match.group(2)
        if current_name in pins:
            raise SnapshotError(
                f"{path}:{line_number}: duplicate package pin: {current_name}"
            )
    finish_pin()
    if not pins:
        raise SnapshotError(f"{path}: lock contains no package pins")
    return pins


def _resolved_dependencies(
    path: Path,
    *,
    direct: dict[str, str],
    scope: str,
) -> dict[str, dict[str, str]]:
    pins = read_lock(path)
    missing = sorted(set(direct) - set(pins))
    if missing:
        raise SnapshotError(
            f"{path}: direct dependencies missing from lock: {', '.join(missing)}"
        )
    mismatched = sorted(
        name for name, version in direct.items() if pins[name] != version
    )
    if mismatched:
        details = ", ".join(
            f"{name}=={direct[name]} (lock has {pins[name]})" for name in mismatched
        )
        raise SnapshotError(f"{path}: direct dependency versions differ: {details}")
    return {
        name: {
            "package_url": f"pkg:pypi/{quote(name, safe='')}@{quote(version, safe='')}",
            "relationship": "direct" if name in direct else "indirect",
            "scope": scope,
        }
        for name, version in sorted(pins.items())
    }


def build_manifests(root: Path) -> dict[str, dict[str, object]]:
    """Build the exact persistent lock manifests."""
    _validate_project(root / "pyproject.toml")
    runtime_input = root / "requirements.in"
    definitions = (
        ("requirements.txt", "requirements.in", False, "runtime"),
        *(
            (
                f"requirements-{audience}.txt",
                f"requirements-{audience}.in",
                True,
                "development",
            )
            for audience in AUDIENCES
        ),
    )
    manifests: dict[str, dict[str, object]] = {}
    for lock_name, input_name, extends_runtime, scope in definitions:
        direct = direct_requirements(
            root / input_name,
            runtime_input=runtime_input if extends_runtime else None,
        )
        manifests[lock_name] = {
            "name": lock_name,
            "file": {"source_location": lock_name},
            "resolved": _resolved_dependencies(
                root / lock_name, direct=direct, scope=scope
            ),
        }
    return manifests


def _run(root: Path, output: Path) -> None:
    payload = {"manifests": build_manifests(root.resolve())}
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        "Dependency snapshot generated: "
        + ", ".join(
            f"{name}={len(manifest['resolved'])}"
            for name, manifest in payload["manifests"].items()
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    try:
        _run(arguments.root, arguments.output)
    except (OSError, SnapshotError) as error:
        print(f"dependency snapshot error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
